<?php

use Illuminate\Database\Seeder;

class OfficeLocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('office_locations')->insert([

            [
                'id' => 'CAN',
                'name' => 'Canada',
                'country' => 'Canada',
                'countryId' => 'CAN',
                'email' => 'canada@packsmartinc.com',
                'headquarter' => true,
                'address' => '111C Snidercroft Rd.',
                'zip-code' => 'L4K 2J8',
                'city' => 'Concord, Ontario',
                'phone' => '+1 905 760 0077',
            ],
            [
                'id' => 'IND',
                'name' => 'Asia',
                'country' => 'India',
                'countryId' => 'IND',
                'email' => 'asia@packsmartinc.com',
                'headquarter' => false,
                'address' => '705, Bldg-1, Sector 1, MBP, Mahape',
                'zip-code' => '400710',
                'city' => 'Navi-Mumbai, Maharashtra, India',
                'phone' => '+91-773-814-1120',
            ],
            [
                'id' => 'USA',
                'name' => 'United States of America',
                'country' => 'Contact us',
                'countryId' => 'USA',
                'email' => 'usa@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'JPN',
                'name' => 'Japan',
                'country' => 'Contact us',
                'countryId' => 'JPN',
                'email' => 'japan@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'RUS',
                'name' => 'Eastern Europe',
                'country' => 'Contact us',
                'countryId' => 'RUS',
                'email' => 'easterneurope@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'IDN',
                'name' => 'Oceania',
                'country' => 'Contact us',
                'countryId' => 'IDN',
                'email' => 'info@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'BRA',
                'name' => 'Latin America & Caribbean',
                'country' => 'Contact us',
                'countryId' => 'BRA',
                'email' => 'southamerica@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'ZA',
                'name' => 'Africa',
                'country' => 'Contact us',
                'countryId' => 'ZA',
                'email' => 'africa@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'FRA',
                'name' => 'Western Europe',
                'country' => 'Contact us',
                'countryId' => 'FRA',
                'email' => 'westerneurope@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            [
                'id' => 'AU',
                'name' => 'Australia',
                'country' => 'Contact us',
                'countryId' => 'AU',
                'email' => 'australia@packsmartinc.com',
                'headquarter' => false,
                'address' => null,
                'zip-code' => null,
                'city' => null,
                'phone' => null,
            ],
            /*
                [
                    'id' => 'CAN',
                    'name' => 'Pack-Smart Inc. Headquarters',
                    'country' => 'Canada',
                    'countryId' => 'CAN',
                    'address' => '111C Snidercroft Rd.',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => 'L4K 2J8',
                    'city' => 'Concord, Ontario',
                    'phone' => '+1 905 760 0077',
                    'fax' => null,
                    'email' => 'ecardozo@packsmartinc.com',
                    'headquarter' => true,
                ],
                [
                    'id' => 'USA',
                    'name' => 'AdTech Graphics',
                    'country' => 'USA',
                    'countryId' => 'USA',
                    'address' => '8166 Liberty Way',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => '14416',
                    'city' => 'Bergen, New York',
                    'phone' => '610-698-3097',
                    'fax' => null,
                    'email' => 'usa@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'IDN',
                    'name' => 'Pack-Smart Indonesia',
                    'country' => 'Indonesia',
                    'countryId' => 'IDN',
                    'address' => '32 Kav. 3-4, Tempo Scan Tower',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => '12950',
                    'city' => 'Kota Jakarta Selatan',
                    'phone' => null,
                    'fax' => null,
                    'email' => 'info@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'SAU',
                    'name' => 'Al Hilal Electronic Printing Co. Ltd.',
                    'country' => 'Kingdom of Saudi Arabia',
                    'countryId' => 'SAU',
                    'address' => null,
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => null,
                    'city' => null,
                    'phone' => '+966-1-4780373/4731385',
                    'fax' => null,
                    'email' => 'saudiarabia@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'RUS',
                    'name' => 'Nissa DigiSpace',
                    'country' => 'Russia',
                    'countryId' => 'RUS',
                    'address' => '4A/2, Mukomolny Proezd',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => '123290',
                    'city' => 'Moscow',
                    'phone' => '+7 495 956 7770',
                    'fax' => null,
                    'email' => 'russia@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'MEX',
                    'name' => 'Aristarco, s.a. de c.v.',
                    'country' => 'Mexico',
                    'countryId' => 'MEX',
                    'address' => 'Sanchez Azcona 217',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => '03020',
                    'city' => 'Mexico  D.F.',
                    'phone' => '+52 55 56396124',
                    'fax' => null,
                    'email' => 'mexico@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'KOR',
                    'name' => 'Saekyung Machinery LTD',
                    'country' => 'Korea',
                    'countryId' => 'KOR',
                    'address' => null,
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => null,
                    'city' => 'Gangham, Seoul',
                    'phone' => '+82-2-562-2723',
                    'fax' => null,
                    'email' => 'korea@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'JPN',
                    'name' => 'DKSH Japan KK.',
                    'country' => 'Japan',
                    'countryId' => 'JPN',
                    'address' => '4-6, 5-Chome Nishi Nippori',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => '116-0013',
                    'city' => 'Arakawa-Ku, Tokyo',
                    'phone' => null,
                    'fax' => null,
                    'email' => 'japan@packsmartinc.com',
                    'headquarter' => false,
                ],
                [
                    'id' => 'BRA',
                    'name' => 'Pack-Smart Brazil',
                    'country' => 'Brazil',
                    'countryId' => 'BRA',
                    'address' => 'Distrito Industrial III - Bauru/SP - CEP: 17064-857',
                    'lat' => null,
                    'lng' => null,
                    'street' => null,
                    'zip-code' => null,
                    'city' => 'Sao Paulo',
                    'phone' => '14 2106-2352',
                    'fax' => null,
                    'email' => 'alfb@alfb.com.br',
                    'headquarter' => false,
                ],
    */
        ]);
    }
}
